version: '3'

services:
    healthchecker:
        build:
            context: ../
            dockerfile: healthchecker/Dockerfile-QA
            args:
                http_proxy: ${HTTP_PROXY}
                https_proxy: ${HTTPS_PROXY}