FROM php:8.1-cli

# Dev tools
RUN apt-get update && apt-get install -y mc nano git vim bash-completion telnet libssl-dev && rm -r /var/lib/apt/lists/*

RUN docker-php-ext-install sockets

# Common extension dependencies
RUN apt-get update && apt-get install -y libssl-dev libc-client2007e-dev libkrb5-dev \
    && rm -r /var/lib/apt/lists/*

# Composer
RUN curl -o ./composer-setup.php https://getcomposer.org/installer \
    && php composer-setup.php --no-ansi --install-dir=/usr/local/bin --filename=composer --version=1.10.26 \
    && rm -rf composer-setup.php

COPY . /var/www

WORKDIR /var/www

RUN composer install

# Tests
RUN ./vendor/bin/phpunit tests \
    && ./vendor/bin/php-cs-fixer fix --dry-run -v --using-cache=null src \
    && ./vendor/bin/phpstan analyse -l max -c docker/phpstan/phpstan.neon src